from almalinux:9 
run dnf install nginx -y  #To install or add our favours on top of base os
EXPOSE 80  # To say the user about the port opened by the container
CMD ["nginx", "-g", "daemon off;"] #The command helps to start/run the nginx 

