from almalinux:9 
#To install or add our favours on top of base os
run dnf install nginx -y  
#To say the user about the port opened by the container
EXPOSE 80  
#The command helps to start/run the nginx
CMD ["nginx", "-g", "daemon off;"]  

